name: Code style check

on: [ push, workflow_dispatch ]

jobs:
  check:
    name: Code style check
    runs-on: ubuntu-latest
    container: vaskozlov/gcc-clang-cmake

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install clang-format
        run: |
          apt install -y clang-format-17 clang-format-18

      - name: Run clang-format-diff
        run: bash ./scripts/tools/check_code_format.sh
