name: hosted-ninja-vcpkg-cacheoff
on: [ push, workflow_dispatch ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    # The Benchmark package on Ubuntu 22.04 LTS is problematic whereas this
    # Docker container is based on Debian bookworm and has a newer version.
    container: gcc:13
    strategy:
      fail-fast: false
      matrix:
        build_shared_libs: [OFF, ON]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: Dump the content of $RUNNER_TEMP
        run: find $RUNNER_TEMP
        shell: bash
      - name: Dump the content of $RUNNER_WORKSPACE
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Prints output of run-vcpkg's action
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}'"

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg
          testPreset: ninja-multi-vcpkg
